<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title><?php echo $this->escape($this->title); ?></title>
<link rel="stylesheet" type="text/css" media="screen"
	href="<?php echo $this->baseUrl;?>/css/site.css" />

<?php
/**
 * @todo move to controller
 */
if($this->controller == 'whiteboard') { ?>
<link rel="stylesheet" href="<?php echo $this->baseUrl;?>/css/myngle.css" type="text/css" />
<script src="<?php echo $this->baseUrl;?>/js/mootools.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl;?>/js/action.js" type="text/javascript"></script>

{$headerVar}
{$headerVar}
{$headerVar}

{[_x]}
{$y}
{$z}
{[x_]}


<?php
if ($this->action == 'live') {
	?>
<script type="text/javascript">
  type = <?php echo $this->role;?>;
  skype = '<?php echo $this->className;?>';
	</script>
</head>
<body onload="load();">
	<?php
} else { ?>
<script language="javascript">
	function Navigate(type){
		var skype = $('skypeID').value.trim();
		if(skype == ''){
			alert('Please type in your Skype ID');
			return;
		}
		$('skypeID').value = skype
		$("number_type").value = type;
		document.sel_login.submit();
	}
</script>
</head>
<body>
<?php
}
} else { 
echo '</head><body>'; 
} 
?>