#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2



_SEARCHREQUEST = descriptor.Descriptor(
  name='SearchRequest',
  full_name='SearchRequest',
  filename='search.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='query', full_name='SearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_SEARCHRESPONSE = descriptor.Descriptor(
  name='SearchResponse',
  full_name='SearchResponse',
  filename='search.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='SearchResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)



class SearchRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHREQUEST

class SearchResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SEARCHRESPONSE


_SEARCHSERVICE = descriptor.ServiceDescriptor(
  name='SearchService',
  full_name='SearchService',
  index=0,
  options=None,
  methods=[
  descriptor.MethodDescriptor(
    name='Search',
    full_name='SearchService.Search',
    index=0,
    containing_service=None,
    input_type=_SEARCHREQUEST,
    output_type=_SEARCHRESPONSE,
    options=None,
  ),
])

class SearchService(service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _SEARCHSERVICE
class SearchService_Stub(SearchService):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _SEARCHSERVICE

